# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nexus_trading_pb2 as nexus__trading__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nexus_trading_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradingServiceStub(object):
    """Services
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMarketData = channel.stream_stream(
                '/nexus.trading.TradingService/StreamMarketData',
                request_serializer=nexus__trading__pb2.MarketData.SerializeToString,
                response_deserializer=nexus__trading__pb2.TradingSignal.FromString,
                _registered_method=True)
        self.StreamLevel1 = channel.stream_stream(
                '/nexus.trading.TradingService/StreamLevel1',
                request_serializer=nexus__trading__pb2.Level1Data.SerializeToString,
                response_deserializer=nexus__trading__pb2.TradingSignal.FromString,
                _registered_method=True)
        self.StreamLevel2 = channel.stream_stream(
                '/nexus.trading.TradingService/StreamLevel2',
                request_serializer=nexus__trading__pb2.Level2Data.SerializeToString,
                response_deserializer=nexus__trading__pb2.TradingSignal.FromString,
                _registered_method=True)
        self.SubmitOrder = channel.unary_unary(
                '/nexus.trading.TradingService/SubmitOrder',
                request_serializer=nexus__trading__pb2.Order.SerializeToString,
                response_deserializer=nexus__trading__pb2.Order.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/nexus.trading.TradingService/GetPositions',
                request_serializer=nexus__trading__pb2.Empty.SerializeToString,
                response_deserializer=nexus__trading__pb2.PositionList.FromString,
                _registered_method=True)


class TradingServiceServicer(object):
    """Services
    """

    def StreamMarketData(self, request_iterator, context):
        """Market Data Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLevel1(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLevel2(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitOrder(self, request, context):
        """Order Management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamMarketData': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamMarketData,
                    request_deserializer=nexus__trading__pb2.MarketData.FromString,
                    response_serializer=nexus__trading__pb2.TradingSignal.SerializeToString,
            ),
            'StreamLevel1': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamLevel1,
                    request_deserializer=nexus__trading__pb2.Level1Data.FromString,
                    response_serializer=nexus__trading__pb2.TradingSignal.SerializeToString,
            ),
            'StreamLevel2': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamLevel2,
                    request_deserializer=nexus__trading__pb2.Level2Data.FromString,
                    response_serializer=nexus__trading__pb2.TradingSignal.SerializeToString,
            ),
            'SubmitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOrder,
                    request_deserializer=nexus__trading__pb2.Order.FromString,
                    response_serializer=nexus__trading__pb2.Order.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=nexus__trading__pb2.Empty.FromString,
                    response_serializer=nexus__trading__pb2.PositionList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.trading.TradingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.trading.TradingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradingService(object):
    """Services
    """

    @staticmethod
    def StreamMarketData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nexus.trading.TradingService/StreamMarketData',
            nexus__trading__pb2.MarketData.SerializeToString,
            nexus__trading__pb2.TradingSignal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLevel1(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nexus.trading.TradingService/StreamLevel1',
            nexus__trading__pb2.Level1Data.SerializeToString,
            nexus__trading__pb2.TradingSignal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLevel2(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nexus.trading.TradingService/StreamLevel2',
            nexus__trading__pb2.Level2Data.SerializeToString,
            nexus__trading__pb2.TradingSignal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.trading.TradingService/SubmitOrder',
            nexus__trading__pb2.Order.SerializeToString,
            nexus__trading__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.trading.TradingService/GetPositions',
            nexus__trading__pb2.Empty.SerializeToString,
            nexus__trading__pb2.PositionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
